version: "3.3"

services:
  breedbase:
    image: nmorales3142/nicksbreedbase:1.2
    depends_on:
      - breedbase_db
    container_name: breedbase_web
    ports:
      - 7080:8080
      - 25:25
    environment:
    #  - MODE=DEVELOPMENT
    #  - DATABASE_HOST=breedbase_db
    #  - DATABASE_NAME=empty_fixture
    #  - DATABASE_USER=postgres
    #  - DATABASE_PASSWORD=postgres
    #  - DATABASE_OPERATOR=janedoe
      - PGPASSFILE=/home/production/.pgpass
    volumes:
      - type: bind
        source: ./sgn_local_docker.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
    #  - type: bind
    #    source: ${HOME}/cxgn/sgn
    #    target: /home/production/cxgn/sgn
    #  - type: bind
    #    source: ${HOME}/cxgn/DroneImageScripts
    #    target: /home/production/cxgn/DroneImageScripts
    #  - type: bind
    #    source: ${HOME}/cxgn/imagesol
    #    target: /home/production/cxgn/imagesol
    #  - type: bind
    #    source: ${HOME}/cxgn/R_libs
    #    target: /home/production/cxgn/R_libs
    #  - type: bind
    #    source: ${HOME}/cxgn/perl-local-lib
    #    target: /home/production/cxgn/local-lib
    #  - type: bind
    #    source: ${HOME}/archive
    #    target: /home/production/archive
    #  - type: bind
    #    source: ${HOME}/tmp
    #    target: /home/production/tmp
    #  - type: bind
    #    source: ${HOME}/cache
    #    target: /home/production/cache
    #  - type: bind
    #    source: ${HOME}/cluster
    #    target: /home/production/cluster
    #  - type: bind
    #    source: ${HOME}/blast
    #    target: /home/production/blast
    #  - type: bind
    #    source: ${HOME}/images
    #    target: /home/production/public/images
  breedbase_db:
    image: nmorales3142/nicksbreedbasepostgres:1.2
    container_name: breedbase_db
    #volumes:
    #  - type: bind
    #    source: ${HOME}/pgdata
    #    target: /var/lib/postgresql/data
